id: A53340A40
base_file: f5FB0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:08:18.945814
  last_modified_at: 2022-06-15 20:08:18.945818
