id: A53340A40
base_file: f33E4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:08:18.944535
  last_modified_at: 2022-06-15 20:08:18.944541
