id: A53340A40
base_file: fFA6A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:08:18.949837
  last_modified_at: 2022-06-15 20:08:18.949841
